#!/bin/bash
# scrape_and_push.sh
# Scrapes MTBO events, verifies output, and pushes to git.

# Configuration
OUTPUT_FILE="data/events/mtbo_events.json" # The umbrella file
OUTPUT_DIR="data/events" # The directory with the event files
MIN_SIZE_BYTES=100 # Minimum expected size in bytes (safeguard)
LOG_FILE="scraper.log"

# Ensure we are in the project directory
cd "$(dirname "$0")"

# Sync with remote repository (ensure we have latest source)
echo "Syncing with remote repository at $(date)" >> "$LOG_FILE"
if ! git pull --rebase >> "$LOG_FILE" 2>&1; then
    echo "Git pull failed. Aborting." >> "$LOG_FILE"
    exit 1
fi

# 1. Run Scraper
echo "Starting scrape at $(date)" >> "$LOG_FILE"
# Pass --commit-msg-file. Output points to the Umbrella Index file.
./scrape_now.sh --output "$OUTPUT_FILE" --commit-msg-file .commit_msg "$@" >> "$LOG_FILE" 2>&1
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo "Scraper failed with exit code $EXIT_CODE. Aborting." >> "$LOG_FILE"
    exit $EXIT_CODE
fi

# 2. Verify Output
if [ ! -f "$OUTPUT_FILE" ]; then
    echo "Output index $OUTPUT_FILE missing. Aborting." >> "$LOG_FILE"
    exit 1
fi
if [ ! -d "$OUTPUT_DIR" ]; then
    echo "Output directory $OUTPUT_DIR missing. Aborting." >> "$LOG_FILE"
    exit 1
fi

# Check against previous file size if it exists (using git version)
# For directory, we check total size.
get_dir_size() {
    du -sb "$1" 2>/dev/null | cut -f1 || echo 0
}

# Check data directory size
FILE_SIZE=$(get_dir_size "$OUTPUT_DIR")

if [ "$FILE_SIZE" -lt "$MIN_SIZE_BYTES" ]; then
    echo "Output directory size ($FILE_SIZE bytes) is suspiciously small. Aborting commit." >> "$LOG_FILE"
    exit 1
fi

# 3. Git Commit and Push
# Check if there are changes in either index or data
if git diff --quiet "$OUTPUT_FILE" "$OUTPUT_DIR"; then
    echo "No changes to $OUTPUT_FILE or $OUTPUT_DIR." >> "$LOG_FILE"
else
    echo "Changes detected. Retrieving stats..." >> "$LOG_FILE"

    # Read commit message from file generated by scraper
    if [ -f .commit_msg ]; then
        COMMIT_MSG=$(cat .commit_msg)
        rm .commit_msg
    else
        COMMIT_MSG="Update MTBO events: $(date +'%Y-%m-%d')"
    fi

    echo "Commit message: $COMMIT_MSG" >> "$LOG_FILE"

    # Stage the directory (new/modified/deleted files) and index
    git add "$OUTPUT_FILE" "$OUTPUT_DIR"
    if git commit -m "$COMMIT_MSG" >> "$LOG_FILE" 2>&1; then
        if git push >> "$LOG_FILE" 2>&1; then
            echo "Pushed changes to git." >> "$LOG_FILE"
        else
            echo "Git push failed. Please check $LOG_FILE" >> "$LOG_FILE"
            exit 1
        fi
    else
        echo "Git commit failed. Changes not pushed. Please check $LOG_FILE" >> "$LOG_FILE"
        exit 1
    fi
fi

echo "Scrape and push completed successfully at $(date)" >> "$LOG_FILE"
