name: Dependabot Auto-Approve & Merge

on:
  pull_request_target:
    branches: ["main"]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Only run for Dependabot
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        # v2.5.0
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve and Enable Auto-Merge for non-major updates
        # Only approve if it's NOT a major version bump
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
