name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install uv
        # v5
        uses: astral-sh/setup-uv@e58605a9b6da7c637471fab8847a5e5a6b8df081
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run Ruff
        run: uv run ruff check .

      - name: Run Ruff Format
        run: uv run ruff format --check .

      - name: Run Mypy
        run: uv run mypy src/

      - name: Run Pytest
        run: uv run pytest tests/ -v
